/**
 * Swagger First Rest Api 鏂囨。
 * user 妯″潡api鏂囨。
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface OrderDTO { 
    addr?: string;
    buyerId?: number;
    id?: number;
    orderCloseDate?: Date;
    orderCreateDate?: Date;
    payChannel?: number;
    payFinCd?: string;
    sellerId?: number;
    status?: number;
    tel?: string;
}
