/**
 * Swagger First Rest Api 鏂囨。
 * user 妯″潡api鏂囨。
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface User { 
    addr?: string;
    id?: number;
    name?: string;
    password?: string;
    roleName?: string;
    tel?: string;
    username?: string;
    wechatOpenid?: string;
}
